### ISSUE TITLE
Pyre with gevent

### ISSUE THREAD

**Issue by tangb** [zeromq/pyre#120]
Hi

I'm trying to use Pyre with bottle and gevent but I got some exceptions:
```
>> python3 test.py
Init green socket Thread-1
----->SETUP EVENTS Thread-1
READ is not NONE
WRITE is not NONE
Init green socket Thread-1
----->SETUP EVENTS Thread-1
READ is not NONE
WRITE is not NONE
Init zsocket Thread-2
Init zsocket Thread-2
Init zsocket Thread-2
Init zsocket Thread-2
Init green socket Thread-3
----->SETUP EVENTS Thread-3
READ is not NONE
WRITE is not NONE
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "test.py", line 41, in __pyre_task
    node = Pyre('TEST')
  File "/usr/local/lib/python3.4/dist-packages/pyre/pyre.py", line 52, in __init__
    self.actor = ZActor(self._ctx, PyreNode, self._outbox)
  File "/usr/local/lib/python3.4/dist-packages/pyre/zactor.py", line 55, in __init__
    self.pipe.wait()
  File "/usr/local/lib/python3.4/dist-packages/pyre/zsocket.py", line 62, in wait
    msg = self.recv()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 261, in recv
    self._wait_read()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 170, in _wait_read
    assert self.__readable.ready(), "Only one greenlet can be waiting on this event"
AttributeError: 'NoneType' object has no attribute 'ready'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pyre/zactor.py", line 58, in run
    self.shim_handler(*self.shim_args, **self.shim_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pyre/pyre_node.py", line 54, in __init__
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/pyre/pyre_node.py", line 507, in run
    self._pipe.signal()
  File "/usr/local/lib/python3.4/dist-packages/pyre/zsocket.py", line 54, in signal
    self.send(struct.pack("Q", signal_value))
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 229, in send
    self.__state_changed()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 131, in __state_changed
    self.__writable.set()
AttributeError: 'NoneType' object has no attribute 'set'


----->CLEANUP EVENTS Thread-2
Exception ignored in: <bound method ZSocket.__del__ of <pyre.zsocket.ZSocket object at 0x7f3978b0e288>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 78, in __del__
    self.close()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 82, in close
    self.__cleanup_events()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 91, in __cleanup_events
    self.__writable.set()
AttributeError: 'NoneType' object has no attribute 'set'
----->CLEANUP EVENTS Thread-2
Exception ignored in: <bound method ZSocket.__del__ of <pyre.zsocket.ZSocket object at 0x7f3978b0e228>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 78, in __del__
    self.close()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 82, in close
    self.__cleanup_events()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 91, in __cleanup_events
    self.__writable.set()
AttributeError: 'NoneType' object has no attribute 'set'
----->CLEANUP EVENTS Thread-2
Exception ignored in: <bound method ZSocket.__del__ of <pyre.zsocket.ZSocket object at 0x7f3978ba5768>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 78, in __del__
    self.close()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 82, in close
    self.__cleanup_events()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 91, in __cleanup_events
    self.__writable.set()
AttributeError: 'NoneType' object has no attribute 'set'
----->CLEANUP EVENTS Thread-2
Exception ignored in: <bound method ZSocket.__del__ of <pyre.zsocket.ZSocket object at 0x7f3978b0e1c8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 78, in __del__
    self.close()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 82, in close
    self.__cleanup_events()
  File "/usr/local/lib/python3.4/dist-packages/zmq/green/core.py", line 91, in __cleanup_events
    self.__writable.set()
AttributeError: 'NoneType' object has no attribute 'set'
^C2017-09-11 12:09:10,089 root.<module> +120: ERROR    [19136] Exception:
Traceback (most recent call last):
  File "test.py", line 118, in <module>
    time.sleep(1.0)
KeyboardInterrupt
END
```

Like you can see I added some logs to understand what's happening.
I replaced all "import zmq" I found in Pyre sources like explained [here](http://pyzmq.readthedocs.io/en/latest/api/zmq.green.html) but it seems Pyre does not call correctly the green socket version and I don't understand why.

Second weird point is even if the thread-3 appears to call green socket, when it tries to use self.__writable, the variable is None... 

Maybe some expert eyes can help me fixing it :smiley: 

I attached my test source but make sure to replace all "import zmq" by "import zmq.green as zmq" in all pyre source files to reproduce the issue.
[test.txt](https://github.com/zeromq/pyre/files/1292186/test.txt)

It seems checking if self.__writeable or self.__readable is not None (and call __setup_events) before using it in zmq/green/core.py fixed the problem but there is surely a better fix directly in Pyre module.

Thank you for your help

**Comment by tangb** [comment]
I found the problem: super constructor call doesn't refer to correct parent class. I proposed a PR in zsocket file.
