### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kotobuki09** [zeromq/pyre#161]
During my installation for BeagleBone Black, I got this issue. Does anyone know what causes this problem?

> pip3 install https://github.com/zeromq/pyre/archive/master.zip
Downloading/unpacking https://github.com/zeromq/pyre/archive/master.zip
  Downloading master.zip (unknown size): 53kB downloaded
  Running setup.py (path:/tmp/pip-zfc2w121-build/setup.py) egg_info for package from https://github.com/zeromq/pyre/archive/master.zip
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'extra_requires'
      warnings.warn(msg)

Downloading/unpacking pyzmq (from zeromq-pyre==0.3.4)
  Downloading pyzmq-22.3.0.tar.gz (1.2MB): 1.2MB downloaded
  Running setup.py (path:/tmp/pip-build-hsdx8dn4/pyzmq/setup.py) egg_info for package pyzmq
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-hsdx8dn4/pyzmq/setup.py", line 260
        info(f"Found zmq.h in {include_dir}")
                                           ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-hsdx8dn4/pyzmq/setup.py", line 260

    info(f"Found zmq.h in {include_dir}")

                                       ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-hsdx8dn4/pyzmq
Storing debug log for failure in /root/.pip/pip.log

**Comment by fieldOfView** [comment]
f-strings are supported from Python 3.6, and you seem to be using Python 3.4. Since the readme says pyre is comaptible with Python 3.3, the f-string should probably be changed to something like this:

`info("Found zmq.h in %s" % include_dir)`

**Comment by fieldOfView** [comment]
pyZMQ, a dependency of pyre, does not seem to support Python 3.4 anymore.
