### ISSUE TITLE
artifactv2 is deprecated so workflows don

### ISSUE THREAD

**Issue by sphaero** [zeromq/pyre#165]
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

**Comment by philrhc** [comment]
i'll take a look at this to get #164 merged

**Comment by sphaero** [comment]
Almost there:
```
Push to branch refs/heads/master
/home/runner/work/_actions/ad-m/github-push-action/master/start.sh: line 18: Missing input 'github_token: ${{ secrets.GITHUB_TOKEN }}'.: bad substitution
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:30:21)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 1
}
```

**Comment by philrhc** [comment]
sorry for the radio silence, have been off sick, will take a look at this shortly, 

thanks for all of the help so far

**Comment by philrhc** [comment]
> Almost there:
> 
> ```
> Push to branch refs/heads/master
> /home/runner/work/_actions/ad-m/github-push-action/master/start.sh: line 18: Missing input 'github_token: ${{ secrets.GITHUB_TOKEN }}'.: bad substitution
> Error: Invalid exit code: 1
>     at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:30:21)
>     at ChildProcess.emit (node:events:519:28)
>     at maybeClose (node:internal/child_process:1105:16)
>     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
>   code: 1
> }
> ```

hello, happy new year,
i've fixed this here: https://github.com/zeromq/pyre/pull/168
i will revisit my implementation of set_interface to get that ready for your review.
thanks!

**Comment by philrhc** [comment]
this can be closed now
