### ISSUE TITLE
struct.error: argument out of range

### ISSUE THREAD

**Issue by sphaero** [zeromq/pyre#67]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/arnaud/src/pyre/pyre/zactor.py", line 59, in run
    self.shim_pipe.signal()
  File "/home/arnaud/src/pyre/pyre/zsocket.py", line 51, in signal
    self.send(struct.pack("L", signal_value))
struct.error: argument out of range
```
Happens on x86 machine. Might need Q instead of L
No problems on 64bit though.

**Comment by sphaero** [comment]
fixed by #69
