### ISSUE TITLE
Networking error while running under Docker

### ISSUE THREAD

**Issue by shader** [zeromq/pyre#73]
I'm not sure what exactly the problem is, or if it is even pyre's fault, but I'm getting the following exception when I run a beacon inside a docker container. I'm guessing it has something to do with udp broadcast support.

  Traceback (most recent call last):
    File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
      self.run()
    File "/usr/lib/python2.7/threading.py", line 763, in run
      self.__target(*self.__args, **self.__kwargs)
    File "/usr/lib/python2.7/site-packages/pyre/zactor.py", line 57, in run
      self.shim_handler(*self.shim_args, **self.shim_kwargs)
    File "/usr/lib/python2.7/site-packages/pyre/zbeacon.py", line 64, in __init__
      self.run()
    File "/usr/lib/python2.7/site-packages/pyre/zbeacon.py", line 283, in run
      self.handle_pipe()
    File "/usr/lib/python2.7/site-packages/pyre/zbeacon.py", line 212, in handle_pipe
      self.configure(port)
    File "/usr/lib/python2.7/site-packages/pyre/zbeacon.py", line 195, in configure
      self.prepare_udp()
    File "/usr/lib/python2.7/site-packages/pyre/zbeacon.py", line 71, in prepare_udp
      self._prepare_socket()
    File "/usr/lib/python2.7/site-packages/pyre/zbeacon.py", line 135, in _prepare_socket
      netinf = zhelper.get_ifaddrs()
    File "/usr/lib/python2.7/site-packages/pyre/zhelper.py", line 268, in get_ifaddrs
      si = sockaddr_in.from_address(ifa.ifa_ifu.ifu_broadaddr)
  TypeError: integer expected

**Comment by sphaero** [comment]
Weird, I've never worked with docker so I don't know what its network stack is about. Need to test. Do you have any documentation pointers?

**Comment by Rio** [comment]
I'm using pyre to communicate between containers and don't have any problems right now. I'll check If I'm doing some weird stuff or something.
