### ISSUE TITLE
prevent the sequence number from going beyond 65535

### ISSUE THREAD

**Issue by sphaero** [zeromq/pyre#76]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/people/arnaud/src/pyre/pyre/pyre_peer.py", line 84, in send
    msg.send(self.mailbox)
  File "/home/people/arnaud/src/pyre/pyre/zre_msg.py", line 154, in send
    self._put_number2(self.sequence)
  File "/home/people/arnaud/src/pyre/pyre/zre_msg.py", line 379, in _put_number2
    d = struct.pack('>H', nr)
struct.error: 'H' format requires 0 <= number <= 65535

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/people/arnaud/src/pyre/pyre/zactor.py", line 57, in run
    self.shim_handler(*self.shim_args, **self.shim_kwargs)
  File "/home/people/arnaud/src/pyre/pyre/pyre_node.py", line 52, in __init__
    self.run()
  File "/home/people/arnaud/src/pyre/pyre/pyre_node.py", line 501, in run
    self.recv_api()
  File "/home/people/arnaud/src/pyre/pyre/pyre_node.py", line 189, in recv_api
    self.peers[peer_id].send(msg)
  File "/home/people/arnaud/src/pyre/pyre/pyre_peer.py", line 85, in send
    except zmq.EAGAIN as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```
also fix the zmq.EAGAIN exception (its not an exception)

**Comment by sphaero** [comment]
fixed in #77
