### ISSUE TITLE
Pyre.set_port() doesn't seem to work

### ISSUE THREAD

**Issue by ajanin** [zeromq/pyre#81]
At first I thought it was just a typo in that the argument list of set_port (around line 95 in pyre.py) refers to port_nbt, but the call to self.actor.send uses port_nbr. But even when I switched port_nbt to port_nbr, I got an error:

from pyre import Pyre
import zmq
p = Pyre()
p.set_port(5671)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/tmp/janin/virtualenv/python33.pyre/lib/python3.3/site-packages/pyre/pyre.py", line 100, in set_port
    self.actor.send(port_nbr)
  File "/scratch/tmp/janin/virtualenv/python33.pyre/lib/python3.3/site-packages/pyre/zactor.py", line 78, in send
    return self.pipe.send(*args, **kwargs)
  File "zmq/backend/cython/socket.pyx", line 581, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5447)
  File "zmq/backend/cython/socket.pyx", line 628, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5209)
  File "zmq/backend/cython/socket.pyx", line 168, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:1959)
  File "zmq/utils/buffers.pxd", line 200, in buffers.asbuffer_r (zmq/backend/cython/socket.c:7257)
  File "zmq/utils/buffers.pxd", line 151, in buffers.asbuffer (zmq/backend/cython/socket.c:6686)
TypeError: 5671 does not provide a buffer interface.

This isn't urgent, but I thought I'd pass it on...

 Adam Janin
 janin@icsi.berkeley.edu

**Comment by sphaero** [comment]
Yeah, I know. It's an API call we have never had need for yet. Probably should write a unittest for it

**Comment by WestFlame** [comment]
I think I've successfully set new port by calling:
```
p = Pyre()
p.set_port(b'5671')
```

**Comment by ajanin** [comment]
Cool. Just tested on latest master, and it works. Thanks!

**Comment by ajanin** [comment]
Not sure when it was fixed, but as of master on June 10, 2016, it appears to work.
